export const MockResponseForNearByPlaces = [
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "Jamuna Tourist Attractions Park",
    photos: [[Object]],
    place_id: "ChIJF779fqbHVTcRmYiuSKoM3AI",
    rating: 4.5,
    reference: "ChIJF779fqbHVTcRmYiuSKoM3AI",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 8,
    vicinity: "RC7C+6V4, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "Eimon Ahmed",
    place_id: "ChIJ8aOICwDHVTcRg_zvVOwuB7c",
    plus_code: {
      compound_code: "RCCG+98 Dhaka, Bangladesh",
      global_code: "7MMGRCCG+98",
    },
    reference: "ChIJ8aOICwDHVTcRg_zvVOwuB7c",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    vicinity: "Ka-74/2, Ground Floor of Lal Building, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "300ft view point",
    photos: [[Object]],
    place_id: "ChIJh4RLMgDHVTcRomMxQTOaTlQ",
    rating: 4,
    reference: "ChIJh4RLMgDHVTcRomMxQTOaTlQ",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 30,
    vicinity: "RCFF+PMM, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "Heritage Tree - 300ft Highway",
    photos: [[Object]],
    place_id: "ChIJVzMEewDHVTcR_nsm0vwDcls",
    rating: 5,
    reference: "ChIJVzMEewDHVTcR_nsm0vwDcls",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 5,
    vicinity: "RCGG+6V2",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "Bikers Meetup Police kot",
    photos: [[Object]],
    place_id: "ChIJk0nWJQDHVTcR9cDeIZud-Ls",
    rating: 4,
    reference: "ChIJk0nWJQDHVTcR9cDeIZud-Ls",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 1,
    vicinity: "RCGF+5QF, N301, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "নিকুঞ্জ পর্যটন স্পষ্ট লেক",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJ03nulFXHVTcRRM5sDrXrrRE",
    rating: 4.8,
    reference: "ChIJ03nulFXHVTcRRM5sDrXrrRE",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 6,
    vicinity: "RCF9+CV5, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "ICCB HALL",
    photos: [[Object]],
    place_id: "ChIJM3CQewDHVTcRef2WgGZJ4qI",
    plus_code: {
      compound_code: "RCGG+WP Dhaka, Bangladesh",
      global_code: "7MMGRCGG+WP",
    },
    rating: 4.4,
    reference: "ChIJM3CQewDHVTcRef2WgGZJ4qI",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 5,
    vicinity:
      "International Convention City Bashundhara, Purbachal Expressway, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "Zawad / Umayr Donation",
    place_id: "ChIJYSWjGADHVTcRoehsOysoJ30",
    rating: 5,
    reference: "ChIJYSWjGADHVTcRoehsOysoJ30",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 1,
    vicinity: "RC9R+7PM, Road Number 11, Dhaka",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    icon_background_color: "#13B5C7",
    icon_mask_base_uri:
      "https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet",
    name: "300 fit purbachol",
    photos: [[Object]],
    place_id: "ChIJP5nedwDHVTcRkdcHyY3rP1s",
    plus_code: {
      compound_code: "RCHJ+4P Dhaka, Bangladesh",
      global_code: "7MMGRCHJ+4P",
    },
    rating: 4.3,
    reference: "ChIJP5nedwDHVTcRkdcHyY3rP1s",
    scope: "GOOGLE",
    types: ["tourist_attraction", "point_of_interest", "establishment"],
    user_ratings_total: 6,
    vicinity: "300 Purbachal Expressway, Dhaka",
  },
];
